### ISSUE TITLE
这些脚本可以直接放linux环境跑吗？

### ISSUE THREAD

**Issue by wajika** [evilbutcher/Quantumult_X#15]
我手机上没有安装哪些工具，我看到有个github的worker，是不是配置下secret信息，就可以直接用签到功能了? 
如果是这样，那QX在这里的起什么作用？
另外glados的签到 配置有范例吗？

**Comment by evilbutcher** [comment]
我不太清楚Linux，对于Github Action，是的，配置secret即可，但目前存在问题，还没空修，qx可以理解成运行这些运行脚本的工具。
glados的readme写的比较清楚，可以再看看，哪里不懂再问我

**Comment by wajika** [comment]
> 我不太清楚Linux，对于Github Action，是的，配置secret即可，但目前存在问题，还没空修，qx可以理解成运行这些运行脚本的工具。
> glados的readme写的比较清楚，可以再看看，哪里不懂再问我

glados不支持用账号密码登录了，能用cookie登录吗

**Comment by evilbutcher** [comment]
> > 我不太清楚Linux，对于Github Action，是的，配置secret即可，但目前存在问题，还没空修，qx可以理解成运行这些运行脚本的工具。
> > glados的readme写的比较清楚，可以再看看，哪里不懂再问我
> 
> glados不支持用账号密码登录了，能用cookie登录吗

就是用的Cookie

**Comment by wajika** [comment]
> > > 我不太清楚Linux，对于Github Action，是的，配置secret即可，但目前存在问题，还没空修，qx可以理解成运行这些运行脚本的工具。
> > > glados的readme写的比较清楚，可以再看看，哪里不懂再问我
> > 
> > 
> > glados不支持用账号密码登录了，能用cookie登录吗
> 
> 就是用的Cookie

我还是没找到 你说的readme在哪里，是checkincookie_env.js文件开头那一段吗？ 我看懂actions worker的运作方式，但是没理解为什么要先执行checkincookie_env.js 文件，是提前让脚本自己获取cookie？ 另外checkincookie_env.js应该给哪些环境变量？ 

我只发现check_in.js的环境变量
```
check_in.js 
        env:
          TITLE: ${{ secrets.CHECKIN_TITLE }}
          URL: ${{ secrets.CHECKIN_URL }}
          EMAIL: ${{ secrets.CHECKIN_EMAIL }}
          PASSWORD: ${{ secrets.CHECKIN_PASSWORD }}
```
